# Imagen base con Python
FROM python:3.10-slim

# Definir el directorio de trabajo
WORKDIR /app

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . .

# Exponer el puerto (FastAPI por defecto usa 8000)
EXPOSE 8000

# Comando para ejecutar la app.
CMD ["python", "app.py"]
